// Auto-generated by generate-plugin-sdk.ts - DO NOT EDIT

export type {
	Addon,
	AddonAuthor,
	AddonManifest,
	AddonResolveable,
	AssetsModule,
	ButtonComponent,
	ButtonProps,
	ButtonSize,
	ButtonVariant,
	CardProps,
	CheckboxProps,
	CreateStyles,
	DesignModule,
	DiscordAsset,
	EnumLike,
	FloatingActionButtonProps,
	FontDescriptor,
	FontEntity,
	GhostInputProps,
	IconButtonProps,
	IconPack,
	IconPackManifest,
	IconSlot,
	InputSize,
	InputStatus,
	InternalToastOptions,
	NativeAssociationKey,
	NativeCallOptions,
	NativeClassHandle,
	NativeFFIBridge,
	NativeFFISignature,
	NativeFFIType,
	NativeFFITypeName,
	NativeHandle,
	NativeHookContext,
	NativeHookHandlers,
	NativeHookOptions,
	NativeHookToken,
	NativeObjCBridge,
	NativeObjectHandle,
	NativePluginBridge,
	NativePluginCapability,
	NativePluginError,
	NativePointer,
	NativeStruct,
	NativeThreadPolicy,
	Navigation,
	Plugin,
	PluginContext,
	PluginEntity,
	ResolvedStyles,
	RowButtonProps,
	SegmentedControlProps,
	SegmentedControlState,
	SettingsEntry,
	SettingsScreen,
	SliderProps,
	SplitTextInputProps,
	StackProps,
	StyleSheetSpec,
	StyleSheetSpecOrFactory,
	SwitchProps,
	TableCheckboxRowProps,
	TableRadioRowProps,
	TableRowComponent,
	TableRowGroupProps,
	TableRowGroupTitleProps,
	TableRowIconProps,
	TableRowProps,
	TableSwitchRowProps,
	TextAreaProps,
	TextFieldProps,
	TextInputPassthrough,
	TextInputProps,
	TextProps,
	TextVariant,
	TextWeight,
	Theme,
	ThemeEntity,
	ThemeSemanticColor,
	ToastButton,
	ToastHandle,
	ToastOptions,
	ToastStoreState,
	TrailingTextProps,
	TransitionState,
	UnboundAsset,
} from './_internal';
import type { NativePluginBridge } from './_internal';
import type { ColorString } from './utils';
declare global {
	/** A feature name published by the native module's capability table. */
	type UnboundNativeFeature =
		| 'device.info'
		| 'device.entitlements'
		| 'app.source'
		| 'notifications'
		| 'pip.video'
		| 'chat.avatar'
		| 'chat.messageBubbles'
		| 'toolbox.menu'
		| 'native.evaluateBytecode'
		| 'native.pluginApi';
	/**
	 * The lifecycle status of a native feature on the running build. `unknown` and `unavailable`
	 * both mean "do not call"; only `supported` and `deprecated` are safe.
	 */
	type UnboundNativeFeatureStatus =
		| 'unknown'
		| 'removed'
		| 'deprecated'
		| 'supported'
		| 'unavailable';
	/**
	 * The full metadata record for a native feature. Everything but `name` and `known` is absent
	 * when the feature is not in this build's table.
	 */
	type UnboundNativeFeatureInfo = {
		name: string;
		known: boolean;
		status: UnboundNativeFeatureStatus;
		supported?: boolean;
		introducedIn?: string;
		deprecatedIn?: string;
		removedIn?: string;
		replacement?: UnboundNativeFeature;
	};
	/** Hardware, OS, and install-integrity details for the device Unbound is running on. */
	type UnboundNativeDevice = {
		getModel(): string;
		getiOSVersionString(): string;
		isJailbroken(): boolean;
		isSystemApp(): boolean;
		isVerifiedBuild(): boolean;
		getEntitlements(): Record<string, any>;
		getEntitlementsAsPlist(): string;
	};
	/** How this copy of the app was installed. */
	type UnboundNativeApp = {
		getSource(): string;
	};
	/** Local notification scheduling. */
	type UnboundNativeNotifications = {
		show(
			title?: string,
			body?: string,
			timeDelay?: number,
			soundEnabled?: boolean,
			identifier?: string,
		): string;
	};
	/** Picture-in-picture video playback. */
	type UnboundNativePiP = {
		playVideo(url: string): string | null;
	};
	/**
	 * Native chat appearance controls. The getters read synchronously; every setter hops to the
	 * main queue and returns immediately, so a value read back on the next line may still be stale.
	 */
	type UnboundNativeChat = {
		getAvatarCornerRadius(): number;
		setAvatarCornerRadius(radius?: number): void;
		resetAvatarCornerRadius(): void;
		getMessageBubblesEnabled(): boolean;
		getMessageBubbleLightColor(): ColorString;
		getMessageBubbleDarkColor(): ColorString;
		getMessageBubbleCornerRadius(): number;
		setMessageBubblesEnabled(
			enabled: boolean,
			lightColor?: ColorString,
			darkColor?: ColorString,
		): void;
		setMessageBubbleColors(lightColor?: ColorString, darkColor?: ColorString): void;
		setMessageBubbleCornerRadius(radius?: number): void;
		resetMessageBubbles(): void;
	};
	/** The native toolbox menu, drawn natively so it survives a broken JS bundle. */
	type UnboundNativeToolbox = {
		showMenu(): void;
	};
	/** The raw `UnboundNative` JSI bridge the tweak installs directly on the JS global. */
	type UnboundNativeModule = {
		getNativeModuleVersion(): string;
		supportsFeature(name: UnboundNativeFeature): boolean;
		getFeatureInfo(name: UnboundNativeFeature): UnboundNativeFeatureInfo;
		isFeatureDeprecated(name: UnboundNativeFeature): boolean;
		isFeatureRemoved(name: UnboundNativeFeature): boolean;
		getSupportedFeatures(): UnboundNativeFeature[];
		getDeprecatedFeatures(): UnboundNativeFeature[];
		getRemovedFeatures(): UnboundNativeFeature[];
		/**
		 * Runs Hermes bytecode in the app's JS runtime and returns whatever it evaluates to.
		 * Throws when the buffer is not an `ArrayBuffer`, is empty, or is not Hermes bytecode;
		 * anything the bytecode itself throws propagates too.
		 */
		evaluateBytecode(bytecode: ArrayBuffer, tag?: string): any;
		device: UnboundNativeDevice;
		app: UnboundNativeApp;
		notifications: UnboundNativeNotifications;
		pip: UnboundNativePiP;
		chat: UnboundNativeChat;
		toolbox: UnboundNativeToolbox;
		nativePlugin: NativePluginBridge;
	};
	type UnboundNativePluginModule = NativePluginBridge;
	/**
	 * Build-time token, replaced with a boolean literal by the build's `transform.define`. Folds at
	 * the module-graph level so `if ($$DEV$$)` branches (and any imports inside them) are dead-code
	 * eliminated from production bundles entirely. Use it (not a runtime check) to gate dev-only code.
	 */
	var $$DEV$$: boolean;
	/** The raw `UnboundNative` JSI bridge, installed on the global by the platform loader. */
	var UnboundNative: UnboundNativeModule | undefined;
	var UnboundNativePlugin: UnboundNativePluginModule | undefined;
	var React: typeof import('react');
	var ReactNative: typeof import('react-native');

	interface Window {}
}

export interface UnboundGlobal {
	assets: typeof import('./assets.d.ts');
	fs: typeof import('./fs.d.ts');
	i18n: typeof import('./i18n.d.ts');
	metro: typeof import('./metro/index.d.ts');
	native: typeof import('./native.d.ts');
	patcher: typeof import('./patcher.d.ts');
	settings: typeof import('./settings.d.ts');
	storage: typeof import('./storage.d.ts');
	toasts: typeof import('./toasts.d.ts');
}

declare global {
	interface Window {
		unbound: UnboundGlobal;
	}

	const unbound: Window['unbound'];
}
